apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: simple
  namespace: simple
spec:
  releaseName: simple
  chart:
    spec:
      chart: simple-deploy
      version: ">=0.1.0"
      sourceRef:
        kind: HelmRepository
        name: simple
        namespace: flux-system
  interval: 2m
  install:
    remediation:
      retries: 3
