apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: simple-deploy
  namespace: simple-deploy
spec:
  releaseName: simple-deploy
  chart:
    spec:
      chart: simple-deploy
      version: ">=0.1.0"
      sourceRef:
        kind: HelmRepository
        name: simple-deploy
        namespace: flux-system
  interval: 2m
  install:
    remediation:
      retries: 3
  values:
    name: example
    replicaCount: 1
    image:
      repository: nginx
      tag: "1.16.1"
    resources: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    service:
      type: ClusterIP
      port: 80
    autoscaling:
      enabled: false
